# https://www.graphviz.org/

generate_images:
	# dot -Tpng:cairo -o supervisor_init.png supervisor_init.dot
	dot -Tpng:cairo -o supervision_tree.png supervision_tree.dot

view_images:
	# eog supervisor_init.png &
	eog supervision_tree.png &
