# https://www.graphviz.org/

generate_images:
	dot -Tpng:cairo -o release.png release.dot
	# dot -Tpng:cairo -o host.png host.dot
	# dot -Tpng:cairo -o cluster.png cluster.dot
	# dot -Tpng:cairo -o federation.png federation.dot

view_images:
	eog release.png &
	# eog host.png &
	# eog cluster.png &
	# eog federation.png &
